services:
  mysql:
    image: mysql:8.4
    container_name: ncc_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ncc_db
      MYSQL_USER: ncc_user
      MYSQL_PASSWORD: ncc_pass
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./apps/api
    container_name: ncc_api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ncc_user
      DB_PASSWORD: ncc_pass
      DB_NAME: ncc_db
      DB_SYNC: "true"
      WEB_ORIGIN: http://13.212.248.168:9100
    ports:
      - "9200:3001"

  web:
    build:
      context: ./apps/web
      args:
        NEXT_PUBLIC_API_URL: http://13.212.248.168:9200
    container_name: ncc_web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      API_URL: http://api:3001
      NEXT_PUBLIC_API_URL: http://13.212.248.168:9200
    ports:
      - "9100:3000"

volumes:
  mysql-data:
